apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: app-crds
spec:
  encryptedData:
    password: AgBeN1400TvvYHU2e0EHuequCsRqVvhV8DdBkgUEoWFKKJJD5lDg7vbBXU3CnUIuF7sRXc8WmqwzggPjTcrjnw4NiWIqm9BC3DuY/aWqZNQg+x+Sohq4c/A+pS84xQBVczsjpzlC9x6yYOcLqC9zb3gwGqBMXyEphWvtZu3jKDWb8QDwkUQ6Y8mELMMnGv/aWXqvCYuEUhmDPK0fTD7xy1psYjarXPkNKTwITcL9Cx8s9N+s9M4eCyocF9czyHpJW4bVDiCr41sDjjW29FlhJeE5kerFNtEWxHPbaHjLkUGyY/JQEUwyNOujhkyDQE5dcGXKJTsujRTX8vAv2MKPbdZdj7f0VVqGguFUwRTNV9C/KlrbLml6nSFWg5uVCkQ0TRfH2OAwEGSsXP1d1HnttTG4GX6jXfbt4ID/K3c9iMSw0IclAKRlOk1wpqIbqEnOukKL34DDeLA9iQR60sSfZa8TQ9z/+xVU1xbckEzQVtRYnAdlUZForAWlRcUlosPRN4T+vHxi4iMDM2PCRp8BmiQC6beGJNA3S+Fo5Lh12eqjB6NbPGa8GsmehHtvj3sgUIVLXGK2Ao6OxDsyJn2MjZwhB0sf4UwJJkpONjbxQXlQHbp62T4tRXT/RYUQ3ej1g6N4yojXi6GT1vcbe8PWsppHx6pJTa7LoxECERVCKSbqsZ2S1DHGXdZYrCBxHAra/1vRuc58ZowvFhlDGaE=
    username: AgB1/8XhvMu/95aOeFSF+LyCBosFh/kHSdVkDNMnK3KbUNrfl1HxksVtlYZrBOpOaCPQA7tIs9x7sFFkrAkBLICqeEK/3WwQNFL7mnI5KTc7najaSxJAtH8Sbw4WW4PB4PDmwphDkJ+XJAImBTS5Lib6FwfODEcTvfEYf2pmNMvynxHRxhisWi8XdBXDtX3NydfveXw4eh+cHfshleA+QPXcBC32kP1qnD5GpGb2bxfJ8XQ68xfn8kBcFFIKTPgYAnxgR/jnRQOy/DHBz8lm1eYqL7MaOgSdCaPx1wQvs6OSTNfnc85MiDLF0eAP4TxjWR7WnuNgv2FBa5jIbsiidtUWazdSwicNserc1djlDaCdFRqwHiMEmqZ10HfPciU2GmTWw9cyFbIgmdWMBuNuqs+vg6zHcXA0R92eZ79OvDxA/9GcUYpmTnSeBLJWUZSApfOl1LbiZGG8xeO72J41K6uNHPeK5usb7SioyEvNRYZ07RLqgKC6FWdJRaj9H2s1YZwPTPyGnn2tpMDmoq+DcKPn+RitO2Oseb7J1g/DqADmObWA7CvUNI599N6x8Hr7NmMC/+BlULyhNQ6M/4qtw2URSh+Zr5OYnKtylKRJN5aMVwW3w/j1xfMMrGEpMvtB0SFWNZRkHWMCZv91ZWK3FEo5ct5zMLkOzr6u7L/SBWkH+kx1FUwaLmowKYvkFVtaG/X+LfTg
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: app-crds
